[package]
name = "pagination"
version = "0.1.0"
authors = ["pagination <pagination@qianxin.com>"]
edition = "2021"

[lib]
name = "pagination"
path = "src/lib.rs"

[dependencies]
diesel = { version = "1.4.7", features = ["mysql", "postgres"] }
